### ISSUE TITLE
Pre-workshop checklist

### ISSUE THREAD

**Issue by olexandr-konovalov** [ccp-codima/2020-02-20-lancaster#2]
* Workshop page
- [ ] update location (add room number)
- [ ] update the list of instructors
- [ ] update the list of helpers
- [ ] update schedule: who teaches what and when
- [ ] create etherpad and put links

* Logistics
- [x] fill in workshop request form on the Carpentries website (@alex-konovalov)
- [ ] reminder to fill in the pre-workshop survey
- [ ] reminder to install software in advance (also, we will be able to help on the spot from 9am before the start of the workshop)
- [ ] organise drop-in sessions to help with installation
- [ ] reminder about configuring wi-fi 
- [ ] get link to the results of pre-workshop survey
- [ ] order refreshment breaks and lunches
- [ ] put door signs

* Equipment
- [ ] additional projector and screen
- [ ] borrowed laptops
- [ ] laptop stand
- [ ] extension cables
- [ ] arrange tables
- [ ] spare w-fi guest logins
- [ ] stickies
- [ ] print door signs
- [ ] blue-tack for door signs
- [ ] whiteboard markers
- [ ] Windows virtual machine
